[package]
name = "nakatoshi"
version = "0.1.0"
authors = ["ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2018"
description = "Bitcoin vanity address generator"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ndelvalle/nakatoshi"
repository = "https://github.com/ndelvalle/nakatoshi"
keywords = ["bitcoin", "address", "vanity", "vanity-address"]
categories = ["command-line-utilities"]

[dependencies]
secp256k1 = "0.15.5"
bitcoin = "0.21.0"
clap = "2.33.0"
indicatif = "0.12.0"
time = "0.1.42"
num_cpus = "1.10.1"
rayon = "1.2"
