name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: nakatoshi
            asset_name: nakatoshi-linux-amd64
          - os: windows-latest
            artifact_name: nakatoshi.exe
            asset_name: nakatoshi-windows-amd64
          - os: macos-latest
            artifact_name: nakatoshi
            asset_name: nakatoshi-macos-amd64

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --all --release --locked && strip target/release/nakatoshi && mv target/release/nakatoshi target/release/${{ matrix.artifact_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
